# Generated by Django 5.0.2 on 2024-05-11 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=70)),
                ('podtytul', models.CharField(max_length=70)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteka.ksiazka')),
            ],
        ),
    ]
