# Generated by Django 5.0.2 on 2024-05-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='autor',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='seria',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='status',
            field=models.CharField(choices=[('want to read', 'Want to read'), ('currently reading', 'Currently reading'), ('read', 'Read'), ('did not finish', 'Did not finish')], default='want to read', max_length=30),
        ),
    ]
