# Generated by Django 5.0.2 on 2024-05-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0003_ksiazka_ceneo_url_alter_ksiazka_podtytul_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='ceneo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='podtytul',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='seria',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('want to read', 'Want to read'), ('currently reading', 'Currently reading'), ('read', 'Read'), ('did not finish', 'Did not finish')], default='', max_length=25, null=True),
        ),
    ]
