# Generated by Django 5.0.2 on 2024-05-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0004_alter_ksiazka_ceneo_url_alter_ksiazka_podtytul_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ksiazka',
            old_name='podtytul',
            new_name='podtytuł',
        ),
        migrations.RenameField(
            model_name='ksiazka',
            old_name='tytul',
            new_name='tytuł',
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='gatunek',
            field=models.CharField(choices=[('fantasy', 'fantasy'), ('science fiction', 'science fiction'), ('horror', 'horror'), ('klasyka', 'klasyka'), ('kryminał', 'kryminał'), ('thriller', 'thriller'), ('literatura młodzieżowa', 'literatura młodzieżowa'), ('literatura obyczajowa', 'literatura obyczajowa'), ('romans', 'romans'), ('literatura piękna', 'literatura piękna'), ('powieść historyczna', 'powieść historyczna'), ('powieść przygodowa', 'powieść przygodowa'), ('romantasy', 'romantasy'), ('biografia', 'biografia'), ('literatura podróżnicza', 'literatura podróżnicza'), ('literatura popularnonaukowa', 'literatura popularnonaukowa'), ('literatura dziecięca', 'literatura dziecięca'), ('poradnik', 'poradnik'), ('hobby', 'hobby'), ('poezja', 'poezja')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='gatunek2',
            field=models.CharField(choices=[('fantasy', 'fantasy'), ('science fiction', 'science fiction'), ('horror', 'horror'), ('klasyka', 'klasyka'), ('kryminał', 'kryminał'), ('thriller', 'thriller'), ('literatura młodzieżowa', 'literatura młodzieżowa'), ('literatura obyczajowa', 'literatura obyczajowa'), ('romans', 'romans'), ('literatura piękna', 'literatura piękna'), ('powieść historyczna', 'powieść historyczna'), ('powieść przygodowa', 'powieść przygodowa'), ('romantasy', 'romantasy'), ('biografia', 'biografia'), ('literatura podróżnicza', 'literatura podróżnicza'), ('literatura popularnonaukowa', 'literatura popularnonaukowa'), ('literatura dziecięca', 'literatura dziecięca'), ('poradnik', 'poradnik'), ('hobby', 'hobby'), ('poezja', 'poezja')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
