# Generated by Django 5.0.2 on 2024-05-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0005_rename_podtytul_ksiazka_podtytuł_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='review',
            new_name='opinia',
        ),
        migrations.RemoveField(
            model_name='ksiazka',
            name='gatunek',
        ),
        migrations.RemoveField(
            model_name='ksiazka',
            name='gatunek2',
        ),
    ]
