# Generated by Django 5.0.2 on 2024-05-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0006_rename_review_vote_opinia_remove_ksiazka_gatunek_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='gatunki',
            field=models.ManyToManyField(to='Biblioteka.gatunek'),
        ),
    ]
