# Generated by Django 5.0.2 on 2024-05-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0007_gatunek_ksiazka_gatunki'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ksiazka',
            old_name='podtytuł',
            new_name='podtytul',
        ),
        migrations.RenameField(
            model_name='ksiazka',
            old_name='tytuł',
            new_name='tytul',
        ),
    ]
