# Generated by Django 5.0.2 on 2024-05-12 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0010_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteka.autor'),
        ),
    ]
