# Generated by Django 5.0.2 on 2024-05-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0013_alter_ksiazka_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ksiazka',
            name='autor',
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='autor',
            field=models.ManyToManyField(to='Biblioteka.autor'),
        ),
    ]
