# Generated by Django 5.0.2 on 2024-05-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0014_remove_ksiazka_autor_ksiazka_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ksiazka',
            name='ceneo_url',
        ),
    ]
