# Generated by Django 5.0.6 on 2024-06-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0016_remove_ksiazka_status_polka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polka',
            name='status',
            field=models.CharField(choices=[('', ''), ('1', 'Want to read'), ('2', 'Currently reading'), ('3', 'Read'), ('4', 'Did not finish')], max_length=25),
        ),
    ]
