# Generated by Django 5.0.6 on 2024-06-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0017_alter_polka_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polka',
            name='status',
            field=models.CharField(choices=[('', ''), ('want to read', 'Want to read'), ('currently reading', 'Currently reading'), ('read', 'Read'), ('did not finish', 'Did not finish')], max_length=25),
        ),
    ]
